groups:
  - name: devops-monitoring-alerts
    rules:

      - alert: HighCPUUsage
        expr: system_cpu_usage_percent > 80
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High CPU Usage"
          description: "CPU usage is above 80% for more than 2 minutes."

      - alert: HighMemoryUsage
        expr: system_memory_usage_percent > 85
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High Memory Usage"
          description: "Memory usage is above 85% for more than 2 minutes."

      - alert: HighDiskUsage
        expr: system_disk_usage_percent > 90
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "High Disk Usage"
          description: "Disk usage is above 90% for more than 5 minutes."